name: Build Debug APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Ensure Gradle Wrapper 8.5
        run: |
          chmod +x gradlew || true
          ./gradlew wrapper --gradle-version 8.5
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TradingKIApp-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
